# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true
fortran: false
latex: false
pandoc: false

matrix:
  include:
    - r: 3.1
    - r: 3.2
    - r: 3.3
    - r: oldrel
    - r: release
    - r: devel
    - os: osx
      disable_homebrew: true

after_failure:
  - cat "${RCHECK_DIR}/00install.out"

after_success:
  - cat "${RCHECK_DIR}/00install.out"

notifications:
  email:
    on_success: change
    on_failure: change
