name: R-CI

on:
  push:
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get ansible playbook to check package
        run: curl -Ls https://stewid.github.io/ansible-r-ci/r-ci.yml -o ../r-ci.yml

      - name: Check package
        run: ansible-playbook -i localhost, --extra-vars "r_ci_covr=codecov r_ci_lintr=false" ../r-ci.yml
